/*
Author: Max Kessler <max.e.kessler@gmail.com>
Date: 30.01.2020 20:15

implement the ModelArray Factory that serves as factory for array JSON objects
retrieved via a REST interface; it also servers as a base class for all REST
object array factories; these factories should be used to create array objects
containing Models
*/

import { TypedJSON } from 'typedjson';
import { restGET } from '../utils/rest';
import { ArrayView } from '../views/ArrayView';
import { Model } from './Model';
import {
    Constructor,
    RESTFactory
} from './RESTFactory';

// type that we allow to be used to construct a ModelArray
//  object[]: array of objects that an array should be created from
//  string: query string parameters used to retrieve the array from the REST
//      endpoint
export type ModelArrayType = object[] | string;

export class ModelArrayFactory<T extends Model> extends RESTFactory {
    /**
     * construct an array of Models by calling the REST endpoint, initializing
     * the class fields for each object instance, and appending it to a View
     *
     * @param model array of objects representing the Model instance that should
     *      be created
     * @param view ArrayView to which the ModelArray should be added
     * @param cls class of the Model elements to construct (e.g. Player)
     *
     * @returns void
     */
    public constructToView(
        modelArray: ModelArrayType,
        view: ArrayView,
        cls: Constructor<T>
    ): void {
        let serializer: TypedJSON<T> = new TypedJSON(cls);

        if (typeof(modelArray) === "string") {
            // query string parameters -> get array from REST endpoint
            this.getJsonPromise(modelArray).then(
                (p) => {
                    let array: T[] = this.parseJsonArray(p, serializer);
                    view.setModelArray(array);
                }
                ).catch(
                    (err: Error) => {
                        console.log(err);
                }
            );
        } else {
            let array: T[] = this.parseJsonArray(modelArray, serializer);
            view.setModelArray(array);
        }
    }

    /**
     * get a Promise to the JSON representation of a ModelArray given a set of
     * query string parameters
     * @param qsp query string parameters as URL string as generated by a Filter
     *
     * @returns Promise to a JSON object of the ModelArray
     */
    protected async getJsonPromise(qsp: string): Promise<Model[]> {
        return restGET(this.restHostname + this.restEndpoint + qsp);
    }

    /**
     * parse an array of JSON objects and create an array of `T` objects
     *
     * @param objectArray array of `T` objects to be parsed to T
     * @param serializer TypedJSON serializer to be used to parse `T` objects in
     * `objectArray`
     *
     * @returns T[] array of parsed objects
     */
    private parseJsonArray(
        objectArray: object[],
        serializer: TypedJSON<T>
    ): T[] {
        let TArray: T[] = [];
        for (let index in objectArray) {
            TArray.push(serializer.parse(objectArray[index]));
        }

        return TArray;
    }
}
