/*
Author: Max Kessler <max.e.kessler@gmail.com>
Date: 30.01.2020 20:15

implement the ModelList Factory that serves as factory for list JSON objects
retrieved via a REST interface; it also servers as a base class for all REST
object list factories; these factories should be used to create list objects
containing Models
*/

import { List } from 'tabris-decorators';
import { TypedJSON } from 'typedjson';
import { restGET } from '../utils/rest';
import { ModelListSettable } from '../views/ModelListSettable';
import { Model } from './Model';
import {
    Constructor,
    RESTFactory
} from './RESTFactory';

// type that we allow to be used to construct a ModelList
//  object[]: array of objects that an list should be created from
//  string: query string parameters used to retrieve the array from the REST
//      endpoint
export type ModelListSourceType = object[] | string;

export class ModelListFactory<T extends Model> extends RESTFactory {
    /**
     * construct an list of Models by calling the REST endpoint, initializing
     * the class fields for each object instance, and appending it to a View
     *
     * @param modelListSource object representing the Model instance that should
     *      be created
     * @param view View to which the ModelList should be added
     * @param cls class of the Model elements to construct (e.g. Player)
     *
     * @returns void
     */
    public constructToView(
        modelListSource: ModelListSourceType,
        view: ModelListSettable,
        cls: Constructor<T>
    ): void {
        let serializer: TypedJSON<T> = new TypedJSON(cls);

        if (typeof(modelListSource) === "string") {
            // query string parameters -> get array from REST endpoint
            this.getJsonPromise(modelListSource).then(
                (p) => {
                    let list: List<T> = this.parseJsonArray(p, serializer);
                    view.setModelList(list);
                }
                ).catch(
                    (err: Error) => {
                        console.log(err);
                }
            );
        } else {
            let list: List<T> = this.parseJsonArray(modelListSource, serializer);
            view.setModelList(list);
        }
    }

    /**
     * get a Promise to the JSON representation of a ModelList given a set of
     * query string parameters
     * @param qsp query string parameters as URL string as generated by a Filter
     *
     * @returns Promise to a JSON object of the ModelList
     */
    protected async getJsonPromise(qsp: string): Promise<object[]> {
        return restGET(this.restHostname + this.restEndpoint + qsp);
    }

    /**
     * parse an array of JSON objects and create an list of `T` objects
     *
     * @param objectArray array of `T` objects to be parsed to T
     * @param serializer TypedJSON serializer to be used to parse `T` objects in
     * `objectArray`
     *
     * @returns list of parsed objects
     */
    private parseJsonArray(
        objectArray: object[],
        serializer: TypedJSON<T>
    ): List<T> {
        let TList: List<T> = new List();
        for (let index in objectArray) {
            TList.push(serializer.parse(objectArray[index]));
        }

        return TList;
    }
}
